-- Run in Supabase SQL editor. The Express API uses the server-only service key.
create extension if not exists pgcrypto;
create type public.user_role as enum ('customer','delivery_agent','admin');
create type public.delivery_status as enum ('PLACED','CONFIRMED','PREPARING','READY_FOR_PICKUP','ASSIGNED','PICKED_UP','OUT_FOR_DELIVERY','DELIVERED','FAILED','RETURNED','CANCELLED');
create table public.users (id uuid primary key default gen_random_uuid(), full_name text not null, email text unique not null, phone text not null, password_hash text not null, role public.user_role not null default 'customer', avatar_url text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.addresses (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id), label text not null, address_line text not null, city text not null, state text, postal_code text, latitude numeric(9,6), longitude numeric(9,6), created_at timestamptz not null default now());
create table public.orders (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.users(id), order_number text unique not null, pickup_address_id uuid references public.addresses(id), delivery_address_id uuid references public.addresses(id), total_amount numeric(12,2) not null check(total_amount>=0), status public.delivery_status not null default 'ASSIGNED', priority text not null default 'normal', estimated_delivery_time timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_name text not null, quantity int not null check(quantity>0), price numeric(12,2) not null check(price>=0));
create table public.deliveries (id uuid primary key default gen_random_uuid(), order_id uuid unique not null references public.orders(id), delivery_agent_id uuid not null references public.users(id), assigned_at timestamptz not null default now(), picked_up_at timestamptz, out_for_delivery_at timestamptz, delivered_at timestamptz, status public.delivery_status not null default 'ASSIGNED', delivery_notes text, proof_of_delivery_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.delivery_locations (id uuid primary key default gen_random_uuid(), delivery_id uuid not null references public.deliveries(id) on delete cascade, delivery_agent_id uuid not null references public.users(id), latitude numeric(9,6) not null check(latitude between -90 and 90), longitude numeric(9,6) not null check(longitude between -180 and 180), accuracy numeric, heading numeric, speed numeric, recorded_at timestamptz not null default now());
create table public.delivery_events (id uuid primary key default gen_random_uuid(), delivery_id uuid not null references public.deliveries(id) on delete cascade, status public.delivery_status not null, description text, created_by uuid references public.users(id), created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id), type text not null, title text not null, message text not null, is_read boolean not null default false, created_at timestamptz not null default now());
create index on public.orders(customer_id);create index on public.deliveries(delivery_agent_id,status);create index on public.delivery_locations(delivery_id,recorded_at desc);create index on public.notifications(user_id,is_read);
alter table public.users enable row level security;alter table public.addresses enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.deliveries enable row level security;alter table public.delivery_locations enable row level security;alter table public.delivery_events enable row level security;alter table public.notifications enable row level security;
-- Policies below assume custom JWT claims: role. Create equivalent policies for your auth provider.
create policy "own profile" on public.users for select using (id=auth.uid() or (auth.jwt()->>'role')='admin');
create policy "own addresses" on public.addresses for all using (user_id=auth.uid() or (auth.jwt()->>'role')='admin');
create policy "customer orders" on public.orders for select using (customer_id=auth.uid() or (auth.jwt()->>'role')='admin');
create policy "customer order items" on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or (auth.jwt()->>'role')='admin')));
create policy "assigned deliveries" on public.deliveries for select using (delivery_agent_id=auth.uid() or (select customer_id from public.orders where id=order_id)=auth.uid() or (auth.jwt()->>'role')='admin');
create policy "authorized locations" on public.delivery_locations for select using (exists(select 1 from public.deliveries d join public.orders o on o.id=d.order_id where d.id=delivery_id and (d.delivery_agent_id=auth.uid() or o.customer_id=auth.uid() or (auth.jwt()->>'role')='admin')));
create policy "authorized events" on public.delivery_events for select using (exists(select 1 from public.deliveries d join public.orders o on o.id=d.order_id where d.id=delivery_id and (d.delivery_agent_id=auth.uid() or o.customer_id=auth.uid() or (auth.jwt()->>'role')='admin')));
create policy "own notifications" on public.notifications for all using (user_id=auth.uid() or (auth.jwt()->>'role')='admin');
